### PR TITLE
Add reserved_concurrent_executions parameter

### PR DESCRIPTION
**Pull request by elizabethvenner**
Authors: @elizabethvenner @ mnayal

### CODE REVIEW

**Review by CorinChappy — APPROVED** [review]

**Review by tobyclemson — COMMENTED** [review]
Looks good to me. A test would be nice but if you need to get this in quickly, happy to add one later.

**Comment by tobyclemson** [comment]
One thing, not sure if a default of -1 is the right thing - it might be better to use `null` as this results in the property not even being set.

**Comment by elizabethvenner** [comment]
> Looks good to me. A test would be nice but if you need to get this in quickly, happy to add one later.

What kind of test do you have in mind? Would you want us to add this parameter to the outputs and test this? Or test the functionality, ie try to trigger concurrent lambda functions and verify that only one is running (disclaimer: not sure of the feasibility of the latter)

**Comment by elizabethvenner** [comment]
> One thing, not sure if a default of -1 is the right thing - it might be better to use `null` as this results in the property not even being set.

I used -1 as this is what aws defaults to if you don't try to set it so probably using null would have the same effect. If you think that would be better, I'm happy to change it.

**Comment by tobyclemson** [comment]
> > Looks good to me. A test would be nice but if you need to get this in quickly, happy to add one later.
> 
> What kind of test do you have in mind? Would you want us to add this parameter to the outputs and test this? Or test the functionality, ie try to trigger concurrent lambda functions and verify that only one is running (disclaimer: not sure of the feasibility of the latter)

Normally I use the AWS SDK to check that the parameter has been set on the resource. So no need to output or actually execute the lambda, just check that AWS has been configured properly.

The test harness should allow you to reprovision with a different config value to test this specifically too.

**Comment by tobyclemson** [comment]
> > One thing, not sure if a default of -1 is the right thing - it might be better to use `null` as this results in the property not even being set.
> 
> I used -1 as this is what aws defaults to if you don't try to set it so probably using null would have the same effect. If you think that would be better, I'm happy to change it.

My preference with these modules is to leave it up to AWS when the parameter hasn’t been consumer specified since then if AWS chooses to change the default behaviour, the module won’t need any changes. So better to pass null unless the consumer specifies it.

**Pull request merged**
